// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: todo_transport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateTaskRequest_TaskState int32

const (
	UpdateTaskRequest_UNRESOLVED UpdateTaskRequest_TaskState = 0
	UpdateTaskRequest_COMPLETED  UpdateTaskRequest_TaskState = 1
)

// Enum value maps for UpdateTaskRequest_TaskState.
var (
	UpdateTaskRequest_TaskState_name = map[int32]string{
		0: "UNRESOLVED",
		1: "COMPLETED",
	}
	UpdateTaskRequest_TaskState_value = map[string]int32{
		"UNRESOLVED": 0,
		"COMPLETED":  1,
	}
)

func (x UpdateTaskRequest_TaskState) Enum() *UpdateTaskRequest_TaskState {
	p := new(UpdateTaskRequest_TaskState)
	*p = x
	return p
}

func (x UpdateTaskRequest_TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateTaskRequest_TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_todo_transport_proto_enumTypes[0].Descriptor()
}

func (UpdateTaskRequest_TaskState) Type() protoreflect.EnumType {
	return &file_todo_transport_proto_enumTypes[0]
}

func (x UpdateTaskRequest_TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateTaskRequest_TaskState.Descriptor instead.
func (UpdateTaskRequest_TaskState) EnumDescriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{8, 0}
}

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_todo_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{0}
}

type GetSystemInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Commit         string                 `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	DevModeEnabled bool                   `protobuf:"varint,2,opt,name=dev_mode_enabled,json=devModeEnabled,proto3" json:"dev_mode_enabled,omitempty"`
	Semver         string                 `protobuf:"bytes,3,opt,name=semver,proto3" json:"semver,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_todo_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemInfoResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetSystemInfoResponse) GetDevModeEnabled() bool {
	if x != nil {
		return x.DevModeEnabled
	}
	return false
}

func (x *GetSystemInfoResponse) GetSemver() string {
	if x != nil {
		return x.Semver
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // The unique id for a particular task
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_todo_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_todo_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset is a pagination parameter that defines where to start when counting
	// the list of pipelines to return.
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// limit is a pagination parameter that defines how many pipelines to return
	// per result.
	Limit            int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	ExcludeCompleted bool  `protobuf:"varint,3,opt,name=exclude_completed,json=excludeCompleted,proto3" json:"exclude_completed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_todo_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTasksRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetExcludeCompleted() bool {
	if x != nil {
		return x.ExcludeCompleted
	}
	return false
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_todo_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_todo_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_todo_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Parent        string                      `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	State         UpdateTaskRequest_TaskState `protobuf:"varint,5,opt,name=state,proto3,enum=proto.UpdateTaskRequest_TaskState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_todo_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *UpdateTaskRequest) GetState() UpdateTaskRequest_TaskState {
	if x != nil {
		return x.State
	}
	return UpdateTaskRequest_UNRESOLVED
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_todo_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{9}
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_todo_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returns a list of all ids that were deleted.
	Ids           []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_todo_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTaskResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetScheduledTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // The unique id for a particular task
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledTaskRequest) Reset() {
	*x = GetScheduledTaskRequest{}
	mi := &file_todo_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledTaskRequest) ProtoMessage() {}

func (x *GetScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*GetScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{12}
}

func (x *GetScheduledTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetScheduledTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduledTask *ScheduledTask         `protobuf:"bytes,1,opt,name=scheduled_task,json=scheduledTask,proto3" json:"scheduled_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledTaskResponse) Reset() {
	*x = GetScheduledTaskResponse{}
	mi := &file_todo_transport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledTaskResponse) ProtoMessage() {}

func (x *GetScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*GetScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{13}
}

func (x *GetScheduledTaskResponse) GetScheduledTask() *ScheduledTask {
	if x != nil {
		return x.ScheduledTask
	}
	return nil
}

type ListScheduledTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset is a pagination parameter that defines where to start when counting
	// the list of pipelines to return.
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// limit is a pagination parameter that defines how many pipelines to return
	// per result.
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksRequest) Reset() {
	*x = ListScheduledTasksRequest{}
	mi := &file_todo_transport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksRequest) ProtoMessage() {}

func (x *ListScheduledTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksRequest.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{14}
}

func (x *ListScheduledTasksRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListScheduledTasksRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListScheduledTasksResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScheduledTasks []*ScheduledTask       `protobuf:"bytes,1,rep,name=scheduled_tasks,json=scheduledTasks,proto3" json:"scheduled_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListScheduledTasksResponse) Reset() {
	*x = ListScheduledTasksResponse{}
	mi := &file_todo_transport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksResponse) ProtoMessage() {}

func (x *ListScheduledTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{15}
}

func (x *ListScheduledTasksResponse) GetScheduledTasks() []*ScheduledTask {
	if x != nil {
		return x.ScheduledTasks
	}
	return nil
}

type CreateScheduledTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Expression    string                 `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduledTaskRequest) Reset() {
	*x = CreateScheduledTaskRequest{}
	mi := &file_todo_transport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledTaskRequest) ProtoMessage() {}

func (x *CreateScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{16}
}

func (x *CreateScheduledTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateScheduledTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScheduledTaskRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateScheduledTaskRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type CreateScheduledTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduledTaskResponse) Reset() {
	*x = CreateScheduledTaskResponse{}
	mi := &file_todo_transport_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledTaskResponse) ProtoMessage() {}

func (x *CreateScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{17}
}

func (x *CreateScheduledTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateScheduledTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Parent        string                 `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Expression    string                 `protobuf:"bytes,5,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduledTaskRequest) Reset() {
	*x = UpdateScheduledTaskRequest{}
	mi := &file_todo_transport_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduledTaskRequest) ProtoMessage() {}

func (x *UpdateScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateScheduledTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScheduledTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateScheduledTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateScheduledTaskRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *UpdateScheduledTaskRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type UpdateScheduledTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduledTaskResponse) Reset() {
	*x = UpdateScheduledTaskResponse{}
	mi := &file_todo_transport_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduledTaskResponse) ProtoMessage() {}

func (x *UpdateScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{19}
}

type DeleteScheduledTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduledTaskRequest) Reset() {
	*x = DeleteScheduledTaskRequest{}
	mi := &file_todo_transport_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduledTaskRequest) ProtoMessage() {}

func (x *DeleteScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteScheduledTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteScheduledTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduledTaskResponse) Reset() {
	*x = DeleteScheduledTaskResponse{}
	mi := &file_todo_transport_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduledTaskResponse) ProtoMessage() {}

func (x *DeleteScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_transport_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_todo_transport_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteScheduledTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_todo_transport_proto protoreflect.FileDescriptor

const file_todo_transport_proto_rawDesc = "" +
	"\n" +
	"\x14todo_transport.proto\x12\x05proto\x1a\x12todo_message.proto\"\x16\n" +
	"\x14GetSystemInfoRequest\"q\n" +
	"\x15GetSystemInfoResponse\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\tR\x06commit\x12(\n" +
	"\x10dev_mode_enabled\x18\x02 \x01(\bR\x0edevModeEnabled\x12\x16\n" +
	"\x06semver\x18\x03 \x01(\tR\x06semver\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x0fGetTaskResponse\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.proto.TaskR\x04task\"m\n" +
	"\x10ListTasksRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12+\n" +
	"\x11exclude_completed\x18\x03 \x01(\bR\x10excludeCompleted\"6\n" +
	"\x11ListTasksResponse\x12!\n" +
	"\x05tasks\x18\x01 \x03(\v2\v.proto.TaskR\x05tasks\"c\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\"$\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd9\x01\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06parent\x18\x04 \x01(\tR\x06parent\x128\n" +
	"\x05state\x18\x05 \x01(\x0e2\".proto.UpdateTaskRequest.TaskStateR\x05state\"*\n" +
	"\tTaskState\x12\x0e\n" +
	"\n" +
	"UNRESOLVED\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x01\"\x14\n" +
	"\x12UpdateTaskResponse\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x12DeleteTaskResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\")\n" +
	"\x17GetScheduledTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x18GetScheduledTaskResponse\x12;\n" +
	"\x0escheduled_task\x18\x01 \x01(\v2\x14.proto.ScheduledTaskR\rscheduledTask\"I\n" +
	"\x19ListScheduledTasksRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"[\n" +
	"\x1aListScheduledTasksResponse\x12=\n" +
	"\x0fscheduled_tasks\x18\x01 \x03(\v2\x14.proto.ScheduledTaskR\x0escheduledTasks\"\x8c\x01\n" +
	"\x1aCreateScheduledTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x1e\n" +
	"\n" +
	"expression\x18\x04 \x01(\tR\n" +
	"expression\"-\n" +
	"\x1bCreateScheduledTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9c\x01\n" +
	"\x1aUpdateScheduledTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06parent\x18\x04 \x01(\tR\x06parent\x12\x1e\n" +
	"\n" +
	"expression\x18\x05 \x01(\tR\n" +
	"expression\"\x1d\n" +
	"\x1bUpdateScheduledTaskResponse\",\n" +
	"\x1aDeleteScheduledTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x1bDeleteScheduledTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB%Z#github.com/clintjedwards/todo/protob\x06proto3"

var (
	file_todo_transport_proto_rawDescOnce sync.Once
	file_todo_transport_proto_rawDescData []byte
)

func file_todo_transport_proto_rawDescGZIP() []byte {
	file_todo_transport_proto_rawDescOnce.Do(func() {
		file_todo_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_transport_proto_rawDesc), len(file_todo_transport_proto_rawDesc)))
	})
	return file_todo_transport_proto_rawDescData
}

var file_todo_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_todo_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_todo_transport_proto_goTypes = []any{
	(UpdateTaskRequest_TaskState)(0),    // 0: proto.UpdateTaskRequest.TaskState
	(*GetSystemInfoRequest)(nil),        // 1: proto.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),       // 2: proto.GetSystemInfoResponse
	(*GetTaskRequest)(nil),              // 3: proto.GetTaskRequest
	(*GetTaskResponse)(nil),             // 4: proto.GetTaskResponse
	(*ListTasksRequest)(nil),            // 5: proto.ListTasksRequest
	(*ListTasksResponse)(nil),           // 6: proto.ListTasksResponse
	(*CreateTaskRequest)(nil),           // 7: proto.CreateTaskRequest
	(*CreateTaskResponse)(nil),          // 8: proto.CreateTaskResponse
	(*UpdateTaskRequest)(nil),           // 9: proto.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),          // 10: proto.UpdateTaskResponse
	(*DeleteTaskRequest)(nil),           // 11: proto.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),          // 12: proto.DeleteTaskResponse
	(*GetScheduledTaskRequest)(nil),     // 13: proto.GetScheduledTaskRequest
	(*GetScheduledTaskResponse)(nil),    // 14: proto.GetScheduledTaskResponse
	(*ListScheduledTasksRequest)(nil),   // 15: proto.ListScheduledTasksRequest
	(*ListScheduledTasksResponse)(nil),  // 16: proto.ListScheduledTasksResponse
	(*CreateScheduledTaskRequest)(nil),  // 17: proto.CreateScheduledTaskRequest
	(*CreateScheduledTaskResponse)(nil), // 18: proto.CreateScheduledTaskResponse
	(*UpdateScheduledTaskRequest)(nil),  // 19: proto.UpdateScheduledTaskRequest
	(*UpdateScheduledTaskResponse)(nil), // 20: proto.UpdateScheduledTaskResponse
	(*DeleteScheduledTaskRequest)(nil),  // 21: proto.DeleteScheduledTaskRequest
	(*DeleteScheduledTaskResponse)(nil), // 22: proto.DeleteScheduledTaskResponse
	(*Task)(nil),                        // 23: proto.Task
	(*ScheduledTask)(nil),               // 24: proto.ScheduledTask
}
var file_todo_transport_proto_depIdxs = []int32{
	23, // 0: proto.GetTaskResponse.task:type_name -> proto.Task
	23, // 1: proto.ListTasksResponse.tasks:type_name -> proto.Task
	0,  // 2: proto.UpdateTaskRequest.state:type_name -> proto.UpdateTaskRequest.TaskState
	24, // 3: proto.GetScheduledTaskResponse.scheduled_task:type_name -> proto.ScheduledTask
	24, // 4: proto.ListScheduledTasksResponse.scheduled_tasks:type_name -> proto.ScheduledTask
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_todo_transport_proto_init() }
func file_todo_transport_proto_init() {
	if File_todo_transport_proto != nil {
		return
	}
	file_todo_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_transport_proto_rawDesc), len(file_todo_transport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_todo_transport_proto_goTypes,
		DependencyIndexes: file_todo_transport_proto_depIdxs,
		EnumInfos:         file_todo_transport_proto_enumTypes,
		MessageInfos:      file_todo_transport_proto_msgTypes,
	}.Build()
	File_todo_transport_proto = out.File
	file_todo_transport_proto_goTypes = nil
	file_todo_transport_proto_depIdxs = nil
}
